export const PREBUILT_COMMANDS = [
  { key:'about', category:'Universal', command:'/about', defaultResponse:'This bot is powered by 1-TouchBot. 🤖\n\nType /help to see available commands.', description:'Tell users about your bot', needsSetup:false, setupInstructions:null },
  { key:'rules', category:'Universal', command:'/rules', defaultResponse:'📋 <b>Rules</b>\n\n1. Be respectful\n2. No spam\n3. Follow guidelines', description:'Show community rules', needsSetup:false, setupInstructions:null },
  { key:'links', category:'Universal', command:'/links', defaultResponse:'🔗 <b>Links</b>\n\nChannel: @yourchannel\nWebsite: https://yoursite.com\nSupport: @yoursupport', description:'Show important links', needsSetup:false, setupInstructions:null },
  { key:'contact', category:'Universal', command:'/contact', defaultResponse:'📬 <b>Contact Us</b>\n\nSupport: @yoursupport\nEmail: support@yoursite.com', description:'Show contact information', needsSetup:false, setupInstructions:null },
  { key:'website', category:'Universal', command:'/website', defaultResponse:'🌐 Visit our website:\nhttps://yourwebsite.com', description:'Share your website', needsSetup:false, setupInstructions:null },
  { key:'social', category:'Universal', command:'/social', defaultResponse:'📱 <b>Follow Us</b>\n\nTelegram: @yourchannel\nTwitter: @yourtwitter\nInstagram: @yourinsta', description:'Show social media links', needsSetup:false, setupInstructions:null },
  { key:'referral', category:'Marketing & Growth', command:'/referral', defaultResponse:'👥 <b>Your Referral Link</b>\n\n[REFERRAL_LINK]\n\nShare and earn coins!', description:'Show referral link', needsSetup:true, setupInstructions:'Enable Referral System in Payments settings first.' },
  { key:'invite', category:'Marketing & Growth', command:'/invite', defaultResponse:'📨 Invite friends!\n\nYour link: [REFERRAL_LINK]', description:'Alternative referral command', needsSetup:true, setupInstructions:'Enable Referral System in Payments settings first.' },
  { key:'promo', category:'Marketing & Growth', command:'/promo', defaultResponse:'🎁 <b>Promotions</b>\n\nNo active promotions. Stay tuned!', description:'Show promotions', needsSetup:false, setupInstructions:null },
  { key:'giveaway', category:'Marketing & Growth', command:'/giveaway', defaultResponse:'🎉 <b>Giveaway</b>\n\nNo active giveaway.\n\nJoin @yourchannel to be notified!', description:'Show giveaway info', needsSetup:false, setupInstructions:null },
  { key:'group', category:'Community', command:'/group', defaultResponse:'👥 Join our group:\nhttps://t.me/yourcommunity', description:'Share group link', needsSetup:false, setupInstructions:null },
  { key:'channel', category:'Community', command:'/channel', defaultResponse:'📢 Join our channel:\nhttps://t.me/yourchannel', description:'Share channel link', needsSetup:false, setupInstructions:null },
  { key:'support', category:'Community', command:'/support', defaultResponse:'🆘 <b>Need Help?</b>\n\nContact: @yoursupport\nResponse: within 24 hours', description:'Direct to support', needsSetup:false, setupInstructions:null },
  { key:'faq', category:'Community', command:'/faq', defaultResponse:'❓ <b>FAQ</b>\n\nQ: How to start?\nA: Type /start\n\nQ: Need help?\nA: Type /support', description:'Show FAQ', needsSetup:false, setupInstructions:null },
  { key:'report', category:'Community', command:'/report', defaultResponse:'🚨 Report an issue:\nContact: @yoursupport', description:'Report issues', needsSetup:false, setupInstructions:null },
  { key:'earn', category:'Earnings & Payments', command:'/earn', defaultResponse:'💰 <b>Ways to Earn</b>\n\n1. /referral — Invite friends\n2. Daily bonuses\n3. Giveaways', description:'Show earning methods', needsSetup:false, setupInstructions:null },
  { key:'daily', category:'Earnings & Payments', command:'/daily', defaultResponse:'🎁 Daily bonus coming soon!\n\nCheck back tomorrow.', description:'Daily reward', needsSetup:false, setupInstructions:null },
  { key:'leaderboard', category:'Earnings & Payments', command:'/leaderboard', defaultResponse:'🏆 <b>Leaderboard</b>\n\nTop earners coming soon!', description:'Show top earners', needsSetup:false, setupInstructions:null },
  { key:'wallet', category:'Earnings & Payments', command:'/wallet', defaultResponse:'👛 <b>Wallet</b>\n\n/balance — Check balance\n/deposit — Add funds\n/withdraw — Cash out', description:'Show wallet info', needsSetup:false, setupInstructions:null },
  { key:'rates', category:'Earnings & Payments', command:'/rates', defaultResponse:'💱 <b>Rates</b>\n\n1 USD = [CURRENCY_RATE] [CURRENCY_SYMBOL]\n1 [CURRENCY_SYMBOL] = [USD_RATE] USD', description:'Show exchange rates', needsSetup:true, setupInstructions:'Configure currency in Settings first.' },
  { key:'latest', category:'Content & Media', command:'/latest', defaultResponse:'📰 Latest updates:\n@yourchannel', description:'Direct to latest content', needsSetup:false, setupInstructions:null },
  { key:'news', category:'Content & Media', command:'/news', defaultResponse:'📢 Latest news:\nJoin @yourchannel', description:'Show latest news', needsSetup:false, setupInstructions:null },
  { key:'updates', category:'Content & Media', command:'/updates', defaultResponse:'🔔 Get updates!\nJoin: @yourchannel', description:'Show updates info', needsSetup:false, setupInstructions:null },
  { key:'media', category:'Content & Media', command:'/media', defaultResponse:'🎬 <b>Media</b>\n\nYouTube: https://youtube.com/yourchannel\nTelegram: @yourchannel', description:'Share media links', needsSetup:false, setupInstructions:null },
  { key:'shop', category:'E-commerce', command:'/shop', defaultResponse:'🛒 <b>Our Shop</b>\n\nVisit: https://yourshop.com\nContact: @yoursupport', description:'Direct to shop', needsSetup:false, setupInstructions:null },
  { key:'products', category:'E-commerce', command:'/products', defaultResponse:'📦 <b>Products</b>\n\nhttps://yourshop.com', description:'Show products', needsSetup:false, setupInstructions:null },
  { key:'order', category:'E-commerce', command:'/order', defaultResponse:'🛍️ <b>Order</b>\n\n1. Visit: https://yourshop.com\n2. Contact: @yoursupport', description:'How to order', needsSetup:false, setupInstructions:null },
  { key:'price', category:'E-commerce', command:'/price', defaultResponse:'💲 <b>Prices</b>\n\nhttps://yourshop.com\nOr contact: @yoursupport', description:'Show prices', needsSetup:false, setupInstructions:null },
  { key:'track', category:'E-commerce', command:'/track', defaultResponse:'📦 Track order:\n\nContact with order ID: @yoursupport', description:'Track orders', needsSetup:false, setupInstructions:null },
  { key:'play', category:'Games & Entertainment', command:'/play', defaultResponse:'🎮 Games coming soon!\n\nStay tuned!', description:'Show games menu', needsSetup:false, setupInstructions:null },
  { key:'score', category:'Games & Entertainment', command:'/score', defaultResponse:'🏆 Scores coming soon!', description:'Show user score', needsSetup:false, setupInstructions:null },
  { key:'spin', category:'Games & Entertainment', command:'/spin', defaultResponse:'🎰 Spin coming soon!\n\nCheck back later.', description:'Spin the wheel', needsSetup:false, setupInstructions:null },
  { key:'trivia', category:'Games & Entertainment', command:'/trivia', defaultResponse:'🧠 Trivia coming soon!\n\nJoin @yourchannel.', description:'Trivia game', needsSetup:false, setupInstructions:null },
  { key:'feedback', category:'Customer Service', command:'/feedback', defaultResponse:'📝 Send feedback:\n@yoursupport\nOr: feedback@yoursite.com', description:'Collect feedback', needsSetup:false, setupInstructions:null },
  { key:'complaint', category:'Customer Service', command:'/complaint', defaultResponse:'📢 Complaint:\nContact: @yoursupport\nResponse: 24 hours.', description:'Handle complaints', needsSetup:false, setupInstructions:null },
  { key:'status', category:'Customer Service', command:'/status', defaultResponse:'✅ Status: Online\nAll systems operational.', description:'Show bot status', needsSetup:false, setupInstructions:null },
  { key:'book', category:'Customer Service', command:'/book', defaultResponse:'📅 Book appointment:\n@yoursupport\nOr: https://yoursite.com/book', description:'Booking info', needsSetup:false, setupInstructions:null },
]

export const COMMAND_CATEGORIES = [
  'Universal',
  'Marketing & Growth',
  'Community',
  'Earnings & Payments',
  'Content & Media',
  'E-commerce',
  'Games & Entertainment',
  'Customer Service'
]
