export const PREBUILT_COMMANDS = [
  { key:'about', category:'Universal', command:'/about', defaultResponse:'This bot is powered by BotifyPro. 🤖\n\nType /help to see available commands.', description:'Tell users about your bot', needsSetup:false, setupInstructions:null },
  { key:'rules', category:'Universal', command:'/rules', defaultResponse:'📋 <b>Rules</b>\n\n1. Be respectful to others\n2. No spam or self-promotion\n3. Follow channel guidelines\n4. Have fun!', description:'Show community rules', needsSetup:false, setupInstructions:null },
  { key:'links', category:'Universal', command:'/links', defaultResponse:'🔗 <b>Important Links</b>\n\nChannel: @yourchannel\nWebsite: https://yoursite.com\nSupport: @yoursupport', description:'Show important links', needsSetup:false, setupInstructions:null },
  { key:'contact', category:'Universal', command:'/contact', defaultResponse:'📬 <b>Contact Us</b>\n\nSupport: @yoursupport\nEmail: support@yoursite.com\n\nWe respond within 24 hours.', description:'Show contact information', needsSetup:false, setupInstructions:null },
  { key:'website', category:'Universal', command:'/website', defaultResponse:'🌐 Visit our website:\n\nhttps://yourwebsite.com', description:'Share your website', needsSetup:false, setupInstructions:null },
  { key:'social', category:'Universal', command:'/social', defaultResponse:'📱 <b>Follow Us</b>\n\nTelegram: @yourchannel\nTwitter: @yourtwitter\nInstagram: @yourinsta', description:'Show social media links', needsSetup:false, setupInstructions:null },
  { key:'referral', category:'Marketing & Growth', command:'/referral', defaultResponse:'👥 <b>Your Referral Link</b>\n\n[REFERRAL_LINK]\n\nShare this link and earn coins when friends join!', description:'Show user their referral link', needsSetup:true, setupInstructions:'Enable Referral System in Payments settings first.' },
  { key:'invite', category:'Marketing & Growth', command:'/invite', defaultResponse:'📨 Invite friends and earn rewards!\n\nYour invite link:\n[REFERRAL_LINK]', description:'Alternative referral command', needsSetup:true, setupInstructions:'Enable Referral System in Payments settings first.' },
  { key:'promo', category:'Marketing & Growth', command:'/promo', defaultResponse:'🎁 <b>Current Promotions</b>\n\nNo active promotions right now.\n\nJoin @yourchannel to be notified!', description:'Show current promotions', needsSetup:false, setupInstructions:null },
  { key:'giveaway', category:'Marketing & Growth', command:'/giveaway', defaultResponse:'🎉 <b>Giveaway</b>\n\nNo active giveaway right now.\n\nStay tuned — join @yourchannel!', description:'Show giveaway information', needsSetup:false, setupInstructions:null },
  { key:'group', category:'Community', command:'/group', defaultResponse:'👥 Join our community group:\n\nhttps://t.me/yourcommunity', description:'Share community group link', needsSetup:false, setupInstructions:null },
  { key:'channel', category:'Community', command:'/channel', defaultResponse:'📢 Join our main channel:\n\nhttps://t.me/yourchannel', description:'Share channel link', needsSetup:false, setupInstructions:null },
  { key:'support', category:'Community', command:'/support', defaultResponse:'🆘 <b>Need Help?</b>\n\nContact: @yoursupport\n\nResponse time: within 24 hours', description:'Direct users to support', needsSetup:false, setupInstructions:null },
  { key:'faq', category:'Community', command:'/faq', defaultResponse:'❓ <b>FAQ</b>\n\nQ: How do I start?\nA: Type /start\n\nQ: Need help?\nA: Type /support\n\nQ: How do I earn?\nA: Type /earn', description:'Show frequently asked questions', needsSetup:false, setupInstructions:null },
  { key:'report', category:'Community', command:'/report', defaultResponse:'🚨 Report an issue:\n\nContact: @yoursupport\n\nPlease describe the problem clearly.', description:'Allow users to report issues', needsSetup:false, setupInstructions:null },
  { key:'earn', category:'Earnings & Payments', command:'/earn', defaultResponse:'💰 <b>Ways to Earn</b>\n\n1. /referral — Invite friends\n2. Daily bonuses\n3. Participate in giveaways\n4. Complete tasks', description:'Show ways to earn coins', needsSetup:false, setupInstructions:null },
  { key:'daily', category:'Earnings & Payments', command:'/daily', defaultResponse:'🎁 Daily bonus coming soon!\n\nCheck back tomorrow for rewards.', description:'Daily reward command', needsSetup:false, setupInstructions:null },
  { key:'leaderboard', category:'Earnings & Payments', command:'/leaderboard', defaultResponse:'🏆 <b>Leaderboard</b>\n\nTop earners coming soon!\n\nKeep earning to be #1!', description:'Show top earners', needsSetup:false, setupInstructions:null },
  { key:'wallet', category:'Earnings & Payments', command:'/wallet', defaultResponse:'👛 <b>Your Wallet</b>\n\n/balance — Check balance\n/deposit — Add funds\n/withdraw — Cash out', description:'Show wallet overview', needsSetup:false, setupInstructions:null },
  { key:'rates', category:'Earnings & Payments', command:'/rates', defaultResponse:'💱 <b>Exchange Rates</b>\n\n1 USD = [CURRENCY_RATE] [CURRENCY_SYMBOL]\n1 [CURRENCY_SYMBOL] = [USD_RATE] USD', description:'Show exchange rates', needsSetup:true, setupInstructions:'Configure currency settings in the Currency tab first.' },
  { key:'latest', category:'Content & Media', command:'/latest', defaultResponse:'📰 <b>Latest Updates</b>\n\nFollow our channel for news:\n@yourchannel', description:'Direct to latest content', needsSetup:false, setupInstructions:null },
  { key:'news', category:'Content & Media', command:'/news', defaultResponse:'📢 <b>Latest News</b>\n\nStay updated:\n@yourchannel', description:'Show latest news', needsSetup:false, setupInstructions:null },
  { key:'updates', category:'Content & Media', command:'/updates', defaultResponse:'🔔 <b>Get Updates</b>\n\nJoin: @yourchannel\nEnable notifications!', description:'Show update notifications info', needsSetup:false, setupInstructions:null },
  { key:'media', category:'Content & Media', command:'/media', defaultResponse:'🎬 <b>Our Media</b>\n\nYouTube: https://youtube.com/yourchannel\nTelegram: @yourchannel', description:'Share media links', needsSetup:false, setupInstructions:null },
  { key:'shop', category:'E-commerce', command:'/shop', defaultResponse:'🛒 <b>Welcome to Our Shop</b>\n\nVisit: https://yourshop.com\nOr contact: @yoursupport', description:'Direct users to shop', needsSetup:false, setupInstructions:null },
  { key:'products', category:'E-commerce', command:'/products', defaultResponse:'📦 <b>Our Products</b>\n\nView all products:\nhttps://yourshop.com', description:'Show product catalogue', needsSetup:false, setupInstructions:null },
  { key:'order', category:'E-commerce', command:'/order', defaultResponse:'🛍️ <b>Place an Order</b>\n\n1. Visit: https://yourshop.com\n2. Or contact: @yoursupport\n\nWe reply within 24 hours.', description:'How to place an order', needsSetup:false, setupInstructions:null },
  { key:'price', category:'E-commerce', command:'/price', defaultResponse:'💲 <b>Price List</b>\n\nFull pricing at:\nhttps://yourshop.com\n\nOr contact: @yoursupport', description:'Show price list', needsSetup:false, setupInstructions:null },
  { key:'track', category:'E-commerce', command:'/track', defaultResponse:'📦 Track your order:\n\nContact us with your order ID:\n@yoursupport', description:'Order tracking info', needsSetup:false, setupInstructions:null },
  { key:'play', category:'Games & Entertainment', command:'/play', defaultResponse:'🎮 <b>Games</b>\n\nGames coming soon!\n\nStay tuned for exciting prizes.', description:'Show games menu', needsSetup:false, setupInstructions:null },
  { key:'score', category:'Games & Entertainment', command:'/score', defaultResponse:'🏆 Your Score:\n\nGame scores coming soon!', description:'Show user score', needsSetup:false, setupInstructions:null },
  { key:'spin', category:'Games & Entertainment', command:'/spin', defaultResponse:'🎰 Spin the wheel coming soon!\n\nCheck back later to win prizes.', description:'Spin the wheel game', needsSetup:false, setupInstructions:null },
  { key:'trivia', category:'Games & Entertainment', command:'/trivia', defaultResponse:'🧠 Trivia coming soon!\n\nJoin @yourchannel for updates.', description:'Trivia game', needsSetup:false, setupInstructions:null },
  { key:'feedback', category:'Customer Service', command:'/feedback', defaultResponse:'📝 <b>Share Feedback</b>\n\nSend to: @yoursupport\nOr email: feedback@yoursite.com\n\nThank you!', description:'Collect user feedback', needsSetup:false, setupInstructions:null },
  { key:'complaint', category:'Customer Service', command:'/complaint', defaultResponse:'📢 <b>Submit Complaint</b>\n\nContact: @yoursupport\nWe respond within 24 hours.', description:'Handle complaints', needsSetup:false, setupInstructions:null },
  { key:'status', category:'Customer Service', command:'/status', defaultResponse:'✅ <b>System Status</b>\n\nBot Status: Online\nAll systems operational.', description:'Show bot status', needsSetup:false, setupInstructions:null },
  { key:'book', category:'Customer Service', command:'/book', defaultResponse:'📅 <b>Book Appointment</b>\n\nContact: @yoursupport\nOr visit: https://yoursite.com/book', description:'Booking/appointment info', needsSetup:false, setupInstructions:null },
]

export const COMMAND_CATEGORIES = [
  'Universal',
  'Marketing & Growth',
  'Community',
  'Earnings & Payments',
  'Content & Media',
  'E-commerce',
  'Games & Entertainment',
  'Customer Service'
]
