export const PREBUILT_COMMANDS = [
  { key:'about', category:'Universal', command:'/about', defaultResponse:'This bot is powered by BotifyPro. 🤖', description:'Tell users about your bot', needsSetup:false, setupInstructions:null },
  { key:'rules', category:'Universal', command:'/rules', defaultResponse:'📋 Rules:\n\n1. Be respectful\n2. No spam\n3. Follow channel guidelines', description:'Show bot/community rules', needsSetup:false, setupInstructions:null },
  { key:'links', category:'Universal', command:'/links', defaultResponse:'🔗 Our Links:\n\nChannel: @yourchannel\nWebsite: https://yoursite.com\nSupport: @yoursupport', description:'Show important links', needsSetup:false, setupInstructions:null },
  { key:'contact', category:'Universal', command:'/contact', defaultResponse:'📬 Contact us:\n\nSupport: @yoursupport\nEmail: support@yoursite.com', description:'Show contact information', needsSetup:false, setupInstructions:null },
  { key:'website', category:'Universal', command:'/website', defaultResponse:'🌐 Visit our website: https://yourwebsite.com', description:'Share your website link', needsSetup:false, setupInstructions:null },
  { key:'social', category:'Universal', command:'/social', defaultResponse:'📱 Follow us:\n\nTelegram: @yourchannel\nTwitter: @yourtwitter\nInstagram: @yourinsta', description:'Show social media links', needsSetup:false, setupInstructions:null },
  { key:'referral', category:'Marketing & Growth', command:'/referral', defaultResponse:'👥 Your referral link: [REFERRAL_LINK]\n\nInvite friends and earn coins!', description:'Show user their referral link', needsSetup:true, setupInstructions:'Enable Referral System in Payments settings first.' },
  { key:'invite', category:'Marketing & Growth', command:'/invite', defaultResponse:'📨 Invite friends!\n\nYour invite link: [REFERRAL_LINK]', description:'Alternative referral command', needsSetup:true, setupInstructions:'Enable Referral System in Payments settings first.' },
  { key:'promo', category:'Marketing & Growth', command:'/promo', defaultResponse:'🎁 Current Promotions:\n\nNo active promotions right now. Stay tuned!', description:'Show current promotions', needsSetup:false, setupInstructions:null },
  { key:'giveaway', category:'Marketing & Growth', command:'/giveaway', defaultResponse:'🎉 Giveaway Info:\n\nNo active giveaway right now.\n\nJoin @yourchannel to be notified!', description:'Show giveaway information', needsSetup:false, setupInstructions:null },
  { key:'group', category:'Community', command:'/group', defaultResponse:'👥 Join our community:\n\nhttps://t.me/yourcommunity', description:'Share community group link', needsSetup:false, setupInstructions:null },
  { key:'channel', category:'Community', command:'/channel', defaultResponse:'📢 Join our channel:\n\nhttps://t.me/yourchannel', description:'Share channel link', needsSetup:false, setupInstructions:null },
  { key:'support', category:'Community', command:'/support', defaultResponse:'🆘 Need help?\n\nContact: @yoursupport\n\nResponse time: within 24 hours', description:'Direct users to support', needsSetup:false, setupInstructions:null },
  { key:'faq', category:'Community', command:'/faq', defaultResponse:'❓ FAQ:\n\nQ: How do I start?\nA: Type /start\n\nQ: Need help?\nA: Type /support', description:'Show frequently asked questions', needsSetup:false, setupInstructions:null },
  { key:'report', category:'Community', command:'/report', defaultResponse:'🚨 To report an issue:\n\nContact: @yoursupport', description:'Allow users to report issues', needsSetup:false, setupInstructions:null },
  { key:'earn', category:'Earnings & Payments', command:'/earn', defaultResponse:'💰 Ways to earn:\n\n1. /referral — Invite friends\n2. Daily bonuses\n3. Giveaways', description:'Show ways to earn coins', needsSetup:false, setupInstructions:null },
  { key:'daily', category:'Earnings & Payments', command:'/daily', defaultResponse:'🎁 Daily bonus coming soon!\n\nCheck back tomorrow.', description:'Daily reward command', needsSetup:false, setupInstructions:null },
  { key:'leaderboard', category:'Earnings & Payments', command:'/leaderboard', defaultResponse:'🏆 Top earners leaderboard coming soon!', description:'Show top earners', needsSetup:false, setupInstructions:null },
  { key:'wallet', category:'Earnings & Payments', command:'/wallet', defaultResponse:'👛 Your Wallet:\n\n/balance — Check balance\n/deposit — Add funds\n/withdraw — Cash out', description:'Show wallet overview', needsSetup:false, setupInstructions:null },
  { key:'rates', category:'Earnings & Payments', command:'/rates', defaultResponse:'💱 Exchange Rates:\n\n1 USD = [CURRENCY_RATE] [CURRENCY_SYMBOL]\n1 [CURRENCY_SYMBOL] = [USD_RATE] USD', description:'Show exchange rates', needsSetup:true, setupInstructions:'Configure currency settings in the Currency tab first.' },
  { key:'latest', category:'Content & Media', command:'/latest', defaultResponse:'📰 Latest Updates:\n\nFollow our channel: @yourchannel', description:'Direct to latest content', needsSetup:false, setupInstructions:null },
  { key:'news', category:'Content & Media', command:'/news', defaultResponse:'📢 Latest News:\n\nJoin our channel: @yourchannel', description:'Show latest news', needsSetup:false, setupInstructions:null },
  { key:'updates', category:'Content & Media', command:'/updates', defaultResponse:'🔔 Get updates!\n\nJoin: @yourchannel\nEnable notifications!', description:'Show update info', needsSetup:false, setupInstructions:null },
  { key:'media', category:'Content & Media', command:'/media', defaultResponse:'🎬 Our Media:\n\nYouTube: https://youtube.com/yourchannel\nTelegram: @yourchannel', description:'Share media links', needsSetup:false, setupInstructions:null },
  { key:'shop', category:'E-commerce', command:'/shop', defaultResponse:'🛒 Welcome to our shop!\n\nVisit: https://yourshop.com\nOr contact: @yoursupport', description:'Direct users to shop', needsSetup:false, setupInstructions:null },
  { key:'products', category:'E-commerce', command:'/products', defaultResponse:'📦 Our Products:\n\nhttps://yourshop.com', description:'Show product catalogue', needsSetup:false, setupInstructions:null },
  { key:'order', category:'E-commerce', command:'/order', defaultResponse:'🛍️ To order:\n\n1. Visit: https://yourshop.com\n2. Or contact: @yoursupport', description:'How to place an order', needsSetup:false, setupInstructions:null },
  { key:'price', category:'E-commerce', command:'/price', defaultResponse:'💲 Pricing:\n\nVisit: https://yourshop.com\nOr contact: @yoursupport', description:'Show price list', needsSetup:false, setupInstructions:null },
  { key:'track', category:'E-commerce', command:'/track', defaultResponse:'📦 Track order:\n\nContact with order ID: @yoursupport', description:'Order tracking info', needsSetup:false, setupInstructions:null },
  { key:'play', category:'Games & Entertainment', command:'/play', defaultResponse:'🎮 Games coming soon!\n\nStay tuned for exciting prizes.', description:'Show games menu', needsSetup:false, setupInstructions:null },
  { key:'score', category:'Games & Entertainment', command:'/score', defaultResponse:'🏆 Your Score:\n\nGame scores coming soon!', description:'Show user score', needsSetup:false, setupInstructions:null },
  { key:'spin', category:'Games & Entertainment', command:'/spin', defaultResponse:'🎰 Spin the wheel coming soon!\n\nCheck back later.', description:'Spin the wheel game', needsSetup:false, setupInstructions:null },
  { key:'trivia', category:'Games & Entertainment', command:'/trivia', defaultResponse:'🧠 Trivia coming soon!\n\nJoin: @yourchannel for updates.', description:'Trivia game', needsSetup:false, setupInstructions:null },
  { key:'feedback', category:'Customer Service', command:'/feedback', defaultResponse:'📝 Send feedback to: @yoursupport\n\nOr email: feedback@yoursite.com', description:'Collect user feedback', needsSetup:false, setupInstructions:null },
  { key:'complaint', category:'Customer Service', command:'/complaint', defaultResponse:'📢 Submit complaint:\n\nContact: @yoursupport\nWe respond within 24 hours.', description:'Handle complaints', needsSetup:false, setupInstructions:null },
  { key:'status', category:'Customer Service', command:'/status', defaultResponse:'✅ Bot Status: Online\n\nAll systems operational.', description:'Show bot status', needsSetup:false, setupInstructions:null },
  { key:'book', category:'Customer Service', command:'/book', defaultResponse:'📅 Book appointment:\n\nContact: @yoursupport\nOr visit: https://yoursite.com/book', description:'Booking info', needsSetup:false, setupInstructions:null },
]

export const COMMAND_CATEGORIES = [
  'Universal',
  'Marketing & Growth',
  'Community',
  'Earnings & Payments',
  'Content & Media',
  'E-commerce',
  'Games & Entertainment',
  'Customer Service'
]
